version: '3'

services:
  jupyterhub:
    build:
      context: ..
      dockerfile: ./util/Dockerfile
    command: bash /etc/jupyterhub/start.sh
    container_name: jupyterhub
    volumes:
      - jupyterhub_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/jupyterhub
    expose:
      - "8000"
    environment:
      - DOCKER_JUPYTER_IMAGE=jupyter/minimal-notebook:latest
    restart: unless-stopped
    networks:
      - jupyterhub-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - jupyterhub
    restart: unless-stopped
    networks:
      - jupyterhub-network

networks:
  jupyterhub-network:
    driver: bridge

volumes:
  jupyterhub_data: